# Generated by Django 3.2.6 on 2021-10-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garages',
            old_name='phone',
            new_name='mobile',
        ),
    ]
