# Generated by Django 3.2.6 on 2021-10-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_phone_garages_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garages',
            old_name='mobile',
            new_name='phone',
        ),
    ]
