# Generated by Django 3.2.6 on 2021-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_mobile_garages_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garages',
            name='phone',
            field=models.IntegerField(blank=True, default='xxxx'),
        ),
    ]
